Repository Dev-FE-2/toy-project2-team2, pull requests merged in 2024-12, with the labels that each got.

#24 feat: Input, Select 컴포넌트,React.FC 수정
  .husky/pre-commit
  src/components/common/Header/index.tsx
  src/components/common/Input/Input.style.ts
  src/components/common/Input/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Select/Select.styled.ts
  src/components/common/Select/index.tsx
  src/components/common/TextArea/TextArea.styled.ts
  src/components/common/TextArea/index.tsx
  src/pages/home/index.tsx
  src/pages/mypage/index.tsx
Labels: feature

#26 feat: 캘린더 컴포넌트 마크업
  package-lock.json
  package.json
  src/assets/img/left_arrow_icon.svg
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/CalendarWrapper.tsx
  src/components/Calendar/Dates.tsx
  src/components/Calendar/Days.tsx
  src/components/Calendar/calendar.styled.ts
  src/components/Calendar/index.tsx
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/index.tsx
  src/components/common/Header/index.tsx
  src/components/schedule/index.tsx
  src/context/CalendarContext.tsx
  src/hooks/useCalendar.ts
  src/layouts/index.ts
  src/pages/schedule/index.tsx
  src/router/index.tsx
  src/styles/theme.ts
  src/types/components/button.ts
  src/types/components/calendar.ts
Labels: feature

#31 chore: Redux 세팅
  package-lock.json
  package.json
  src/components/common/Header/index.tsx
  src/main.tsx
  src/services/getDatas.ts
  src/store/authListener.ts
  src/store/index.ts
  src/store/slices/userInfoSlice.ts
  src/types/store.ts
Labels: chore

#29 feat: 급여내역 조회 페이지 마크업
  src/assets/img/dot_icon.svg
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/index.tsx
  src/components/common/Header/Header.styled.ts
  src/components/common/Header/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/Modal.styled.ts
  src/components/common/Modal/index.tsx
  src/components/common/Select/index.tsx
  src/components/common/TextArea/index.tsx
  src/layouts/main/main.styled.ts
  src/pages/pay-correction/index.tsx
  src/pages/salary-correction/index.tsx
  src/pages/salary/Salay.styled.ts
  src/pages/salary/components/Deduction.tsx
  src/pages/salary/components/Graph.styled.ts
  src/pages/salary/components/Graph.tsx
  src/pages/salary/components/Header.styled.ts
  src/pages/salary/components/Header.tsx
  src/pages/salary/components/SalaryDetailSection.tsx
  src/pages/salary/components/SalarySection.tsx
  src/pages/salary/index.tsx
  src/pages/salary/types/Graph.ts
  src/pages/salary/types/SalaryDetailSection.ts
  src/pages/salary/types/SalarySection.ts
  src/router/index.tsx
  src/types/components/input.ts
  src/types/components/modal.ts
  src/types/components/select.ts
  src/types/components/textarea.ts
Labels: feature

#32 feat: 일정 페이지 마크업
  src/assets/img/plus_icon.svg
  src/components/Button/Button.styled.ts
  src/components/Button/index.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/index.tsx
  src/components/Input/Input.style.ts
  src/components/Input/index.tsx
  src/components/Modal/Modal.styled.ts
  src/components/Modal/index.tsx
  src/components/Select/Select.styled.ts
  src/components/Select/index.tsx
  src/components/TextArea/TextArea.styled.ts
  src/components/TextArea/index.tsx
  src/components/Title/Title.styled.ts
  src/components/Title/index.tsx
  src/components/index.tsx
  src/layouts/index.ts
  src/layouts/main/index.tsx
  src/layouts/schedule/index.tsx
  src/layouts/schedule/schedule.styled.ts
  src/pages/componentExample/index.tsx
  src/pages/home/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/schedule/components/Calendar/Calendar.tsx
  src/pages/schedule/components/Calendar/CalendarHeader.tsx
  src/pages/schedule/components/Calendar/CalendarWrapper.tsx
  src/pages/schedule/components/Calendar/Dates.tsx
  src/pages/schedule/components/Calendar/Days.tsx
  src/pages/schedule/components/Calendar/calendar.styled.ts
  src/pages/schedule/components/Calendar/index.tsx
  src/pages/schedule/components/Detail/DetailItem.tsx
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Detail/detail.styled.ts
  src/pages/schedule/index.tsx
  src/pages/schedule/schedule.styled.ts
  src/pages/schedule/types/calendar.ts
  src/pages/schedule/types/schedule.ts
  src/router/index.tsx
  src/styles/globalStyle.ts
  src/styles/index.ts
  src/types/components/title.ts
  src/types/index.ts
Labels: feature

#34 feat: 급여내역 조회 페이지- 모달 구현
  src/components/Modal/Modal.styled.ts
  src/components/Modal/index.tsx
  src/components/Select/Select.styled.ts
  src/components/Select/index.tsx
  src/components/TextArea/TextArea.styled.ts
  src/pages/salary-correction/index.tsx
  src/pages/salary/Salay.styled.ts
  src/pages/salary/components/CorrectionModal.tsx
  src/pages/salary/components/Graph.styled.ts
  src/pages/salary/components/Header.styled.ts
  src/pages/salary/components/Header.tsx
  src/pages/salary/components/MonthSalaryModal.styled.ts
  src/pages/salary/components/MonthSalaryModal.tsx
  src/pages/salary/components/SalarySection.tsx
  src/pages/salary/components/mockdata.ts
  src/types/components/modal.ts
  src/types/components/select.ts
Labels: feature

#36 feat: MyPage 마크업
  src/pages/mypage/MyPage.styled.ts
  src/pages/mypage/components/ImageBox.styled.ts
  src/pages/mypage/components/ImageBox.tsx
  src/pages/mypage/components/UserInfoBox.styled.ts
  src/pages/mypage/components/UserInfoBox.tsx
  src/pages/mypage/index.tsx
Labels: feature

#38 feat: 일정 페이지 모달 마크업
  src/components/Header/index.tsx
  src/components/Input/Input.style.ts
  src/contexts/CalendarContext.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useCalendar.ts
  src/layouts/schedule/schedule.styled.ts
  src/pages/schedule/components/Calendar/CalendarWrapper.tsx
  src/pages/schedule/components/Calendar/calendar.styled.ts
  src/pages/schedule/components/Calendar/index.ts
  src/pages/schedule/components/Detail/DetailItem.tsx
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Detail/detail.styled.ts
  src/pages/schedule/components/Modal/ScheduleDetailModal.tsx
  src/pages/schedule/components/Modal/ScheduleFormModal.tsx
  src/pages/schedule/components/Modal/scheduleModal.styled.ts
  src/pages/schedule/types/calendar.ts
  src/pages/schedule/types/schedule.ts
  src/types/contexts/calendarContext.ts
  src/types/index.ts
Labels: feature

#40 feat: 급여정정 신청 내역 페이지 마크업
  src/components/Modal/Modal.styled.ts
  src/components/Select/Select.styled.ts
  src/components/Select/index.tsx
  src/layouts/main/main.styled.ts
  src/pages/salary-correction/components/HistoryModal.styled.ts
  src/pages/salary-correction/components/HistoryModal.tsx
  src/pages/salary-correction/components/StatusBadge.styled.ts
  src/pages/salary-correction/components/StatusBadge.tsx
  src/pages/salary-correction/index.tsx
  src/pages/salary-correction/salary-correction.styled.ts
  src/pages/salary/index.tsx
  src/types/components/select.ts
Labels: feature

#42 feat: 로그인 인증기능 개발
  src/components/Header/index.tsx
  src/main.tsx
  src/pages/login/Login.styled.ts
  src/pages/login/index.tsx
  src/router/ProtectedRoute.tsx
  src/router/index.tsx
  src/services/getDatas.ts
  src/store/authListener.ts
  src/store/index.ts
  src/store/slices/loginAuthSlice.ts
  src/store/slices/userInfoSlice.ts
  src/store/userInfoListener.ts
  src/types/store.ts
Labels: feature

#45 feat: 마이페이지 이미지 업로드 기능 추가 및 기타 버그 수정
  .gitignore
  src/components/Header/index.tsx
  src/firebase/index.ts
  src/pages/login/index.tsx
  src/pages/mypage/components/ImageBox.styled.ts
  src/pages/mypage/components/ImageBox.tsx
  src/pages/mypage/components/UploadButton.styled.ts
  src/pages/mypage/components/UploadButton.tsx
  src/pages/mypage/components/UserInfoBox.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/type/ImageBox.ts
  src/pages/mypage/type/UserInfoBox.ts
  src/router/ProtectedRoute.tsx
  src/services/getDatas.ts
  src/services/mypageUpdateService.ts
  src/store/slices/loginAuthSlice.ts
  src/store/userInfoListener.ts
  src/types/store.ts
Labels: feature

#47 feat: 일정 등록 기능 개발
  src/components/Header/index.tsx
  src/components/Input/Input.style.ts
  src/components/index.tsx
  src/contexts/CalendarContext.ts
  src/hooks/index.ts
  src/hooks/useCalendar.ts
  src/hooks/useRedux.ts
  src/pages/mypage/components/UploadButton.tsx
  src/pages/schedule/components/Calendar/Calendar.tsx
  src/pages/schedule/components/Calendar/CalendarWrapper.tsx
  src/pages/schedule/components/Calendar/Dates.tsx
  src/pages/schedule/components/Calendar/calendar.styled.ts
  src/pages/schedule/components/Calendar/index.ts
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Detail/detail.styled.ts
  src/pages/schedule/components/Modal/ScheduleFormModal.tsx
  src/pages/schedule/index.tsx
  src/pages/schedule/types/calendar.ts
  src/pages/schedule/types/schedule.ts
  src/router/ProtectedRoute.tsx
  src/services/getDatas.ts
  src/services/index.ts
  src/services/mypageUpdateService.ts
  src/services/scheduleService.ts
  src/store/index.ts
  src/store/slices/loginAuthSlice.ts
  src/store/slices/scheduleSlice.ts
  src/store/userInfoListener.ts
  src/types/components/index.ts
  src/types/components/title.ts
  src/types/contexts/calendarContext.ts
  src/types/index.ts
  src/types/store.ts
  src/types/store/auth.ts
  src/types/store/index.ts
  src/types/store/schedule.ts
  src/types/store/user.ts
  src/utils/date.ts
  src/utils/index.ts
Labels: feature

#49 feat: 정정신청 내역 + 상세 모달 파이어베이스 데이터 연결
  src/components/Input/Input.style.ts
  src/components/Select/Select.styled.ts
  src/pages/salary-correction/components/HistoryModal.tsx
  src/pages/salary-correction/index.tsx
  src/pages/salary-correction/salary-correction.styled.ts
  src/pages/salary-correction/types/correctionData.ts
  src/pages/salary/Salay.styled.ts
  src/pages/salary/components/CorrectionModal.tsx
  src/pages/salary/components/Graph.tsx
  src/pages/salary/components/Header.tsx
  src/pages/salary/components/MonthSalaryModal.tsx
  src/pages/salary/components/SalaryDetailSection.tsx
  src/pages/salary/components/SalarySection.tsx
  src/pages/salary/index.tsx
  src/pages/salary/types/Graph.ts
  src/pages/salary/types/SalaryDetailSection.ts
  src/pages/salary/types/SalarySection.ts
  src/pages/salary/types/header.ts
  src/pages/salary/types/salaryData.ts
  src/pages/salary/types/salaryPage.ts
  src/services/SalaryService.ts
  src/types/components/select.ts
Labels: feature

#50 feat: 일정 상세 및 모달 기능 개발
  src/pages/schedule/components/Detail/DetailItem.tsx
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Modal/ScheduleDetailModal.tsx
  src/pages/schedule/components/Modal/scheduleModal.styled.ts
  src/pages/schedule/types/schedule.ts
Labels: feature

#52 feat: ActualPayment계산값 사용, select 외부클릭으로 닫기추가
  src/pages/salary/components/CustomDatePicker.tsx
  src/pages/salary/components/Graph.tsx
  src/pages/salary/components/MonthSalaryModal.tsx
  src/pages/salary/index.tsx
  src/pages/salary/types/salaryData.ts
  src/pages/salary/types/salaryPage.ts
  src/services/SalaryService.ts
  src/utils/calculateSalary.ts
Labels: feature

#53 feat: 일정 수정 기능 개발
  src/hooks/useCalendar.ts
  src/pages/schedule/components/Calendar/CalendarHeader.tsx
  src/pages/schedule/components/Calendar/Dates.tsx
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Modal/ScheduleDetailModal.tsx
  src/pages/schedule/components/Modal/ScheduleFormModal.tsx
  src/pages/schedule/types/schedule.ts
  src/services/scheduleService.ts
  src/store/slices/scheduleSlice.ts
Labels: feature

#55 feat: 일정 삭제 기능 개발
  src/pages/schedule/components/Detail/DetailItem.tsx
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/types/schedule.ts
  src/services/scheduleService.ts
  src/store/slices/scheduleSlice.ts
Labels: feature

#59 fix: 로그인 페이지 오류/개선사항 수정
  src/pages/login/index.tsx
Labels: fix

#66 Feat: toastify 적용
  package-lock.json
  package.json
  src/App.tsx
  src/pages/salary-correction/index.tsx
  src/pages/salary/components/CorrectionModal.tsx
  src/pages/salary/index.tsx
  src/services/SalaryService.ts
Labels: feature

#63 fix: 이번달 버튼css, readonly 스타일 수정,월별급여 포인터
  src/components/Input/Input.style.ts
  src/components/Input/index.tsx
  src/components/TextArea/TextArea.styled.ts
  src/components/TextArea/index.tsx
  src/pages/salary-correction/components/HistoryModal.styled.ts
  src/pages/salary-correction/components/HistoryModal.tsx
  src/pages/salary-correction/components/StatusBadge.styled.ts
  src/pages/salary/components/Header.styled.ts
  src/pages/salary/components/Header.tsx
  src/pages/salary/components/MonthSalaryModal.styled.ts
  src/types/components/input.ts
  src/types/components/textarea.ts
Labels: fix

#68 fix: 일정 파트 내 alert, console 삭제 및 toast로 대체
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Modal/ScheduleFormModal.tsx
  src/services/scheduleService.ts
Labels: fix

#69 feat: React-spinners 적용
  package-lock.json
  package.json
  src/components/Loader/LoaderWrapper.tsx
  src/pages/salary-correction/index.tsx
  src/pages/salary/index.tsx
Labels: feature

#71 feat: 캘린더에 일정 표시 기능 개발
  src/hooks/useCalendar.ts
  src/pages/schedule/components/Calendar/Dates.tsx
  src/pages/schedule/components/Calendar/ScheduleListPerDate.tsx
  src/pages/schedule/components/Calendar/calendar.styled.ts
  src/pages/schedule/components/Detail/DetailItem.tsx
  src/pages/schedule/components/Detail/detail.styled.ts
  src/pages/schedule/index.tsx
  src/pages/schedule/schedule.styled.ts
Labels: feature

#73 fix : readme 수정
  README.md
Labels: fix

#76 fix: 마이페이지 수정 버튼 클릭 전 input 선택가능 현상 수정 및 로더 컴포넌트 적용
  src/components/Input/Input.style.ts
  src/components/Input/index.tsx
  src/pages/mypage/components/ImageBox/UploadButton.tsx
  src/pages/mypage/components/UserInfoBox/UserInfoBox.tsx
  src/pages/mypage/index.tsx
  src/router/ProtectedRoute.tsx
  src/types/components/input.ts
Labels: fix

#79 Bug: fetchUserData 호출 시 로더로 인해 깜빡임 문제
  src/components/Modal/Modal.styled.ts
  src/pages/salary/index.tsx
Labels: bug

#81 fix: 이미지 변경 기능 취소시 이전 이미지로 변경 가능하도록 로직 수정 및 관련 파일 경로 수정
  src/pages/mypage/components/ImageBox/ImageBox.styled.ts
  src/pages/mypage/components/ImageBox/ImageBox.tsx
  src/pages/mypage/components/ImageBox/UploadButton.tsx
  src/pages/mypage/components/UploadButton.styled.ts
  src/pages/mypage/components/UploadButton.tsx
  src/pages/mypage/components/UserInfoBox.styled.ts
  src/pages/mypage/components/UserInfoBox.tsx
  src/pages/mypage/components/UserInfoBox/UserInfoBox.tsx
  src/pages/mypage/components/UserInfoUpdateButton.styled.ts
  src/pages/mypage/components/UserInfoUpdateButton.tsx
  src/pages/mypage/index.tsx
  src/services/mypageUpdateService.ts
Labels: fix

#85 refactoring: 마이페이지 리팩토링, 버튼 컴포넌트 중첩 삼항연산자 간소화, 로그인페이지 반응형 작업
  src/components/Button/Button.styled.ts
  src/pages/login/Login.styled.ts
  src/pages/mypage/components/UploadButton.tsx
  src/pages/mypage/components/UserInfoBox.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/type/ImageBox.ts
  src/pages/mypage/type/UserInfoBox.ts
  src/router/ProtectedRoute.tsx
  src/services/MyPageService.ts
  src/services/mypageUpdateService.ts
Labels: refactoring

#84 refactor : Salary페이지 반응형추가, 상태와 UI 분리, any타입 개선
  src/App.tsx
  src/assets/img/dark.png
  src/assets/img/light.png
  src/assets/img/logo_white.png
  src/components/Dot/index.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/Profile.tsx
  src/components/Header/SideBar.tsx
  src/components/Header/index.tsx
  src/components/Modal/Modal.styled.ts
  src/components/SalaryListItem/index.tsx
  src/components/TextArea/TextArea.styled.ts
  src/context/themeContext.tsx
  src/hooks/useCorrectionModal.ts
  src/hooks/useMonthlySalaryModal.ts
  src/hooks/useSalaryData.ts
  src/pages/salary-correction/components/HistoryModal.tsx
  src/pages/salary-correction/salary-correction.styled.ts
  src/pages/salary-correction/types/historyModal.ts
  src/pages/salary/Salay.styled.ts
  src/pages/salary/components/CorrectionModal.tsx
  src/pages/salary/components/CustomDatePicker.tsx
  src/pages/salary/components/Deduction.tsx
  src/pages/salary/components/Graph.tsx
  src/pages/salary/components/Header.styled.ts
  src/pages/salary/components/MonthSalaryModal.tsx
  src/pages/salary/components/SalaryDetailSection.tsx
  src/pages/salary/components/SalarySection.tsx
  src/pages/salary/index.tsx
  src/pages/salary/types/salaryPage.ts
  src/services/SalaryService.ts
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/types/components/select.ts
Labels: refactoring

#86 refact: 일정 파트 리팩토링
  src/assets/img/logo.png
  src/assets/img/logo_white.png
  src/components/Header/Header.styled.ts
  src/hooks/useCorrectionModal.ts
  src/hooks/useMonthlySalaryModal.ts
  src/layouts/main/main.styled.ts
  src/layouts/mypage/mypage.styled.ts
  src/layouts/schedule/schedule.styled.ts
  src/pages/mypage/components/UserInfoBox.tsx
  src/pages/salary/Salay.styled.ts
  src/pages/schedule/components/Calendar/Dates.tsx
  src/pages/schedule/components/Detail/DetailPanel.tsx
  src/pages/schedule/components/Modal/ScheduleFormModal.tsx
  src/services/authService.ts
  src/services/index.ts
  src/services/scheduleService.ts
  src/services/userService.ts
  src/store/slices/scheduleSlice.ts
  src/store/userInfoListener.ts
Labels: refactoring

#87 fix: 리드미에 테스트 계정 추가
  README.md
Labels: docs
